# Generated by Django 6.0.7 on 2026-09-18 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_deliveryarea_order_cancelled_at_order_confirmed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendororder",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_orders",
                to="store.order",
            ),
        ),
    ]
