# Generated by Django 6.0.7 on 2026-09-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_vendororder_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliveryarea",
            options={"ordering": ["city", "area_name"]},
        ),
        migrations.AddField(
            model_name="deliveryarea",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="deliveryarea",
            name="estimated_delivery_minutes",
            field=models.PositiveIntegerField(
                default=45, help_text="Estimated standard delivery time in minutes"
            ),
        ),
        migrations.AddField(
            model_name="deliveryarea",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="deliveryarea",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="deliveryarea",
            name="minimum_order_value",
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="deliveryarea",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="deliveryarea",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
